<template lang="pug">
q-page(padding)
  .centered
    h2 Welcome to Boid Frontier
  .centered
  .full-width.q-ma-md
    .centered.bg-blue.text-white.q-pa-md
      h4
        a(href="https://frontier.boid.com").text-white Boid Frontier Rewards
  .centered.q-mt-md
    q-card(style="width:700px; max-width:90vw").q-pa-md
      .centered
        h4 Getting Started
      .centered.q-ma-md
        p.full-width.q-pa-md.bg-grey-8.text-white(style="border-radius: 15px;") A new version of Boid is under development. You can participate in the testnet phase to earn NFTs, reserve Boid IDs on Mainnet and earn other prizes.
      q-separator
      .row
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h4 1
              p Create a Boid Account, The easiest way is to use an invite link from an existing Boid User. You can ask for a free invite link in the #[a(href="") Telegram] or #[a(href="") Discord].
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h4 2
              p After you have created your Boid Account and logged in you need to run the Folding@Home client application and use your new Boid ID as the username in the application. Make sure you join the Boid Team or your contributions will not be tracked. The Boid F@H Team ID is #[strong 238663]. Download F@H #[a(href="https://foldingathome.org/start-folding/?lng=en") here].
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h4 3
              p Double check that your Boid ID is used as the user account in the Folding@Home application and you are on the boid.com team. Allow the application to run on your computer at least a few hours per day. The longer the application runs the more Boid Power you can generate. You can view your current Boid Power on the Accounts page.
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h4 4
              p Track your progress on the team leaderboard. Your account will receive testnet BOID tokens over time based on your Boid Power. The tokens are automatically staked to your account which increases your BOID token earning rate. Active members might receive real BOID tokens based on your testnet earnings.
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h4 5
              .col
                p Explore each page to try different functions.
                ul
                  li You can unstake, delegate, transfer some BOID on the Wallet page.
                  li You can purchase some PowerMods with your liquid BOID balancce. PowerMods can give you additional power over time or multiply your exisitng power.
                  li You can purchase a Gold account using anchor wallet or directly from an existing Boid account with some BOID balance.
                  li You can also customize your account profile (coming soon), upgrade your sponsored account to a gold account by paying the upgrade cost.
                  li After you upgrade to a gold account you can purchase invites and generate invite links to share with others, you earn a percentage of the power generated by all accounts you invite. You also get paid when someone you invites pays the account upgrade fee.
                  li New features will be added soon so check back often. An automatic faucet will send you some free BOID and Boid Power each day to keep things interesting.
      q-separator(spaced).q-mt-xl
      p.full-width.q-pa-md.bg-grey-8.text-white.q-mt-md(style="border-radius: 15px;") Learn more details about the new Boid on the #[a(href="https://new.docs.boid.com/boidcore/telos/contract-index/index.html").text-amber-2 docs].

</template>

<script lang="ts">
import { Todo, Meta } from "components/models"
import ExampleComponent from "components/ExampleComponent.vue"
import { defineComponent } from "vue"

export default defineComponent({
  name: "IndexPage",
  components: { ExampleComponent },
  data() {
    const todos:Todo[] = [
      {
        id: 1,
        content: "ct1"
      },
      {
        id: 2,
        content: "ct2"
      },
      {
        id: 3,
        content: "ct3"
      },
      {
        id: 4,
        content: "ct4"
      },
      {
        id: 5,
        content: "ct5"
      }
    ]
    const meta:Meta = {
      totalCount: 1200
    }
    return { todos, meta }
  }
})
</script>
