<template lang="pug">
q-page(padding)
  //- .centered
  //-   h2 Boid Core Hub
  .centered
  .centered.q-mt-md
    q-card(style="width:1200px; max-width:90vw").q-pa-md
      .centered.q-ma-md
        .full-width.q-pa-md(style="border-radius: 15px;")
          .centered
            h2 What is boid
          p Boid allows you to contribute your computing power towards important scientific research, earn rewards, and compete against others from around the world. Learn more about boid at #[a(href="https://docs.boid.com" target="_blank").text-warning.text-hover-primary docs.boid.com].
      q-separator
      .centered.q-mt-md
        h2 Getting Started
      .row
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h2 1
              div.q-pl-lg
                h4 Create a Boid Account
                p There is two ways to create a Boid account.
                ul
                  li
                    p Use an invite link from an existing Boid User. You can meet other boid users on the official #[a(href="https://t.me/boidcommunity" target="_blank") Boid Telegram channel].
                  li
                    p Purchase a Boid Account directly on the #[a(href="/join") join] page.

        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h2 2
              div.q-pa-lg
                h4 Join Folding@Home
                p After you have created your Boid Account you should link it to Folding@Home. Follow the #[a(href="https://docs.boid.com/boidcore/modules/folding" target="_blank") F@H Setup instructions].
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h2 3
              div.q-pa-lg
                h4 Keep Folding@Home running
                p Double check that your Boid ID is used as the user account in the Folding@Home application and you are on the boid.com team. Allow the application to run on your computer at least a few hours per day. The longer the application runs the more Boid Power you can generate. You can view your current Boid Power on the Accounts page.
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h2 4
              div.q-pa-lg
                h4 Watch your account power up
                p Track your progress on the team leaderboard. Your account will receive BOID tokens over time based on your Boid Power. The tokens are automatically staked to your account which increases your BOID token earning rate.
        .col-auto
          div.q-pa-md
            .row.items-center.no-wrap.q-gutter-md
              h2 5
              div.q-pa-lg
                h4 Explore Boid
                ul
                  li
                    p You can unstake, delegate, transfer some BOID on the #[a(href="/wallet") Wallet] page.
                  li
                    p  On the #[a(href="/offer") Offers] page you can activate Power Boosters. Boosters can give you additional power over time or multiply your exisitng power.
                  li
                    p If you purchased a Boid Gold Account or upgraded from a sponsored account you can purchase invites and generate invite links to share with others, you earn a percentage of the power generated by all accounts you invite. You also get paid when someone you invites pays the account upgrade fee.
    div(style="height: 20px;").full-width
</template>

<script lang="ts">
import { Todo, Meta } from "components/models"
import ExampleComponent from "components/ExampleComponent.vue"
import { defineComponent } from "vue"

export default defineComponent({
  name: "IndexPage",
  components: { ExampleComponent },
  data() {
    const todos:Todo[] = [
      {
        id: 1,
        content: "ct1"
      },
      {
        id: 2,
        content: "ct2"
      },
      {
        id: 3,
        content: "ct3"
      },
      {
        id: 4,
        content: "ct4"
      },
      {
        id: 5,
        content: "ct5"
      }
    ]
    const meta:Meta = {
      totalCount: 1200
    }
    return { todos, meta }
  }
})
</script>
