<template lang="pug">
q-page(padding)
  div(v-if="page==1")
    .centered.q-mt-md
      //- div(style="width:60px")
      h3.q-mb-sm Join Boid
    .centered
      div(style="max-width: 570px;") To join Boid you can either use an invite code generated by an existing Boid user to create a sponsored account or you can buy a gold account directly.
    .centered.q-mt-md
      div(style="width:570px;max-width:90vw")
        q-separator
        .centered.q-mt-md
          q-form(@submit="validateInput()")
            h5 Sponsored
            .row
              div.text-weight-light You can create a free sponsored Boid account using an invite code from an existing Boid User.
            .row
              div.text-weight-light Sponsored accounts can be upgraded to gold accounts at any time.
            .row
              div.text-weight-light To get an invite code, you can join our #[a(href="https://t.me/boidcommunity") Telegram] and ask.
        .centered.q-mt-md
          h4 {{errorMsg}}
    .centered.q-mt-lg
      div(style="width:570px;max-width:90vw")
        q-separator
        .centered.q-mt-md
          q-form(@submit="startGoldPurchase()")
            h5 Gold Account
            .row
              div.text-weight-light Gold accounts can be purchased at any time using BOID tokens, the cost is based on the length of the Boid ID.
            .row
              div.text-weight-light Gold accounts can be created with a premium Boid ID which is shorter than normal Boid IDs.
            .row
              div.text-weight-light You can pay for the account using a chain account and anchor wallet or directly from an existing Boid Account.
            .row
              div.text-weight-light learn more about BOID tokens #[a(href="https://docs.boid.com/boidcore/tokenomics") here].
            .row.q-gutter-md.items-center.q-mt-md
              .col-auto
                .row
                  h6 Boid ID Prefix
                .row
                  q-input(v-model="boidIDInput" :error="Boolean(errorMsg)" noErrorIcon)
              .col-auto
                .row
                  h6 Cost
                .row
                  h5 {{goldAcctCost.toLocaleString()}} BOID
              .col-auto
                q-btn(label="continue" :disable="boidIDInput.length==0" type="submit")

            //- div(v-if="!link.loggedIn.account")
            //-   q-btn(label="Telos Testnet anchor Login" @click="link.login()")
            //- .row(v-if="link.loggedIn.account").items-center
            //-   div Paying with account: {{ link.loggedIn.account}}
            //-   q-btn(label="logout" @click="link.logout()")
                //- p {{link.loggedIn}}
                //- q-btn(label="l")
                //- .row
                //-   .col
                //-     small You can also make the purchase using any wallet by transfering BOID with the memo:
                //-     q-input(disable v-model="goldPurchaseMemo")
                  //- q-input(v-model="boidIDInput" :error="Boolean(errorMsg)" noErrorIcon)
              //- .col-auto
              //-   .row
              //-     h6 Invite Code
              //-   .row
              //-     q-input(v-model="inviteCode" :error="Boolean(errorMsg)" noErrorIcon)
              //- .col-3.relative-position(style="width:100px; height:75px;")
              //-   q-btn(label="submit" type="submit").absolute-bottom
        .centered.q-mt-md
          h4 {{errorMsg}}
  div(v-if="page==2" )
    .centered.q-mt-md
      //- div(style="width:60px")
      h3 Create Boid Account
    .centered
      div(style="width:700px;max-width:90vw")
        .centered
          div(v-if="sponsorName.length > 0") This account has been sponsored by {{sponsorName}}
    .centered
      new-account-form(style="width:700px;max-width:90vw" :prefix="boidIDInput" :gold="goldPurchase")
</template>

<script lang="ts">
import { PrivateKey, UInt64 } from "anchor-link"
import { Dialog } from "quasar"
import { sysQueries } from "src/lib/queries"

import { defineComponent } from "vue"
import AddKey from "src/components/dialog/AddKey.vue"
import NewAccountForm from "components/NewAccountForm.vue"
import { linkAccount } from "src/stores/linkAccount"
import { link } from "src/lib/linkManager"
import { sysTables } from "src/stores/sysTables"
export default defineComponent({
  setup() {
    return { link: linkAccount() }
  },
  data() {
    return {
      sponsorName: "",
      inviteCode: "",
      boidIDInput: "",
      key: "",
      goldPurchase: false,
      errorMsg: null as string | null,
      page: 1
    }
  },
  components: { NewAccountForm },
  async mounted() {
    sysTables().loadConfig()
    console.log(this.$route.query)
    if (typeof this.$route.query.sponsor == "string" && typeof this.$route.query.code == "string" && typeof this.$route.query.key == "string") {
      this.sponsorName = this.$route.query.sponsor
      this.inviteCode = this.$route.query.code
      this.key = this.$route.query.key
      try {
        this.validateInput(PrivateKey.fromString(this.key))
      } catch (error) {
        console.error(error)
        return this.errorMsg = "Invite code is invalid or expired, try a fresh invite code."
      }
    }
  },
  methods: {
    startGoldPurchase() {
      this.goldPurchase = true
      this.page = 2
    },
    logout() {
      link.logout()
    },
    createAcctModal() {

    },
    async validateInput(key?:PrivateKey) {
      try {
        if (!key) key = PrivateKey.fromString(this.$route.query.key as string)
        const inviteRow = await sysQueries.invite(this.sponsorName, this.inviteCode)
        if (!inviteRow) return this.errorMsg = "Invite code is invalid or expired, try a fresh invite code."
        console.log(key.toPublic().toString())
        console.log(inviteRow.key.toString())

        if (!key.toPublic().equals(inviteRow.key)) return this.errorMsg = "Invite key is not valid for this invite code."
        console.log("ready to sign claim message")
        this.page = 2
      } catch (error) {
        this.errorMsg = "error with invite code input"
      }
    }
  },
  computed: {
    goldAcctCost():number {
      const config = sysTables().config
      if (!config) return 0
      if (this.boidIDInput.length <= config.account.max_premium_prefix.toNumber()) return config.account.premium_purchase_price.toNumber()
      else return config.account.remove_sponsor_price.toNumber()
    },
    goldPurchaseMemo():string {
      return ""
    }
  }

})
</script>
